project_id = "oleozgrhqfxavbmsiecf"

[functions]
  [functions.mcp]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.messaging-webhook]
    verify_jwt = false
  [functions.twilio-webhook]
    verify_jwt = false
