// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/list-businesses.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.91.1";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function jsonResult(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    structuredContent: payload
  };
}
function requireAuth(ctx) {
  return ctx.isAuthenticated() ? null : errorResult("Not authenticated.");
}

// src/lib/mcp/tools/list-businesses.ts
var list_businesses_default = defineTool({
  name: "list_businesses",
  title: "List businesses",
  description: "List the businesses the signed-in user can access, with their id, name and booking page slug. Call this first to get a business_id for the other tools.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const denied = requireAuth(ctx);
    if (denied) return denied;
    const { data, error } = await supabaseForUser(ctx).from("businesses").select("id, name, slug, industry, timezone, email, phone").order("name");
    if (error) return errorResult(error.message);
    return jsonResult({ businesses: data ?? [] });
  }
});

// src/lib/mcp/tools/list-bookings.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^3.25.76";
var list_bookings_default = defineTool2({
  name: "list_bookings",
  title: "List bookings",
  description: "List appointments for a business within an optional date range and status filter. Returns customer, service, staff, time and payment details.",
  inputSchema: {
    business_id: z.string().uuid().describe("Business id from list_businesses."),
    from: z.string().optional().describe("Inclusive ISO 8601 start of the range, e.g. 2026-07-28T00:00:00Z."),
    to: z.string().optional().describe("Exclusive ISO 8601 end of the range."),
    status: z.enum(["pending", "confirmed", "completed", "cancelled", "no_show"]).optional().describe("Only return bookings with this status."),
    limit: z.number().int().optional().describe("Maximum rows to return (default 50, max 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ business_id, from, to, status, limit }, ctx) => {
    const denied = requireAuth(ctx);
    if (denied) return denied;
    const capped = Math.min(Math.max(limit ?? 50, 1), 200);
    let query = supabaseForUser(ctx).from("bookings").select(
      "id, start_time, end_time, status, customer_name, customer_email, customer_phone, notes, total_price, amount_paid, payment_status, services(name, duration_minutes, price), staff(name)"
    ).eq("business_id", business_id).order("start_time", { ascending: true }).limit(capped);
    if (from) query = query.gte("start_time", from);
    if (to) query = query.lt("start_time", to);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, bookings: data ?? [] });
  }
});

// src/lib/mcp/tools/create-booking.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^3.25.76";
var create_booking_default = defineTool3({
  name: "create_booking",
  title: "Create booking",
  description: "Create a new appointment for a business. The end time is derived from the service duration unless an explicit end_time is given.",
  inputSchema: {
    business_id: z2.string().uuid().describe("Business id from list_businesses."),
    service_id: z2.string().uuid().describe("Service id from list_services."),
    start_time: z2.string().describe("ISO 8601 start time of the appointment."),
    end_time: z2.string().optional().describe("ISO 8601 end time. Defaults to start + service duration."),
    customer_name: z2.string().describe("Customer full name."),
    customer_email: z2.string().optional().describe("Customer email address."),
    customer_phone: z2.string().optional().describe("Customer phone number."),
    staff_id: z2.string().uuid().optional().describe("Staff member id from list_staff."),
    notes: z2.string().optional().describe("Internal notes for this appointment."),
    status: z2.enum(["pending", "confirmed"]).optional().describe("Initial status. Defaults to pending.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const denied = requireAuth(ctx);
    if (denied) return denied;
    const supabase = supabaseForUser(ctx);
    const { data: service, error: serviceError } = await supabase.from("services").select("id, duration_minutes, price").eq("id", input.service_id).eq("business_id", input.business_id).maybeSingle();
    if (serviceError) return errorResult(serviceError.message);
    if (!service) return errorResult("Service not found for this business.");
    const start = new Date(input.start_time);
    if (Number.isNaN(start.getTime())) return errorResult("start_time is not a valid date.");
    const end = input.end_time ? new Date(input.end_time) : new Date(start.getTime() + (service.duration_minutes ?? 60) * 6e4);
    if (Number.isNaN(end.getTime())) return errorResult("end_time is not a valid date.");
    const { data, error } = await supabase.from("bookings").insert({
      business_id: input.business_id,
      service_id: input.service_id,
      staff_id: input.staff_id ?? null,
      start_time: start.toISOString(),
      end_time: end.toISOString(),
      customer_name: input.customer_name,
      customer_email: input.customer_email ?? null,
      customer_phone: input.customer_phone ?? null,
      notes: input.notes ?? null,
      status: input.status ?? "pending",
      total_price: service.price ?? null
    }).select("id, start_time, end_time, status").maybeSingle();
    if (error) return errorResult(error.message);
    return jsonResult({ booking: data });
  }
});

// src/lib/mcp/tools/update-booking-status.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^3.25.76";
var update_booking_status_default = defineTool4({
  name: "update_booking_status",
  title: "Update booking status",
  description: "Change the status of an existing appointment, for example to confirm, complete or cancel it.",
  inputSchema: {
    booking_id: z3.string().uuid().describe("Booking id from list_bookings."),
    status: z3.enum(["pending", "confirmed", "completed", "cancelled", "no_show"]).describe("The new status for the appointment.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ booking_id, status }, ctx) => {
    const denied = requireAuth(ctx);
    if (denied) return denied;
    const { data, error } = await supabaseForUser(ctx).from("bookings").update({ status }).eq("id", booking_id).select("id, status, start_time").maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult("Booking not found, or you do not have permission to change it.");
    return jsonResult({ booking: data });
  }
});

// src/lib/mcp/tools/list-customers.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_customers_default = defineTool5({
  name: "list_customers",
  title: "List customers",
  description: "List or search the customers of a business by name, email or phone. Staff accounts only see the customers assigned to them.",
  inputSchema: {
    business_id: z4.string().uuid().describe("Business id from list_businesses."),
    search: z4.string().optional().describe("Free-text match on name, email or phone."),
    limit: z4.number().int().optional().describe("Maximum rows to return (default 50, max 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ business_id, search, limit }, ctx) => {
    const denied = requireAuth(ctx);
    if (denied) return denied;
    const capped = Math.min(Math.max(limit ?? 50, 1), 200);
    let query = supabaseForUser(ctx).from("customers").select("id, name, email, phone, notes, tags, created_at").eq("business_id", business_id).order("name").limit(capped);
    if (search) {
      const term = search.replace(/[%,()]/g, " ").trim();
      if (term) {
        query = query.or(`name.ilike.%${term}%,email.ilike.%${term}%,phone.ilike.%${term}%`);
      }
    }
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, customers: data ?? [] });
  }
});

// src/lib/mcp/tools/create-customer.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z5 } from "npm:zod@^3.25.76";
var create_customer_default = defineTool6({
  name: "create_customer",
  title: "Create customer",
  description: "Add a new customer record to a business's client list.",
  inputSchema: {
    business_id: z5.string().uuid().describe("Business id from list_businesses."),
    name: z5.string().describe("Customer full name."),
    email: z5.string().optional().describe("Customer email address."),
    phone: z5.string().optional().describe("Customer phone number."),
    notes: z5.string().optional().describe("Notes about this customer.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const denied = requireAuth(ctx);
    if (denied) return denied;
    const { data, error } = await supabaseForUser(ctx).from("customers").insert({
      business_id: input.business_id,
      name: input.name,
      email: input.email ?? null,
      phone: input.phone ?? null,
      notes: input.notes ?? null
    }).select("id, name, email, phone").maybeSingle();
    if (error) return errorResult(error.message);
    return jsonResult({ customer: data });
  }
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z6 } from "npm:zod@^3.25.76";
var list_services_default = defineTool7({
  name: "list_services",
  title: "List services",
  description: "List the bookable services of a business, including duration in minutes and price in GBP.",
  inputSchema: {
    business_id: z6.string().uuid().describe("Business id from list_businesses."),
    include_inactive: z6.boolean().optional().describe("Include services that are currently switched off. Defaults to false.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ business_id, include_inactive }, ctx) => {
    const denied = requireAuth(ctx);
    if (denied) return denied;
    let query = supabaseForUser(ctx).from("services").select("id, name, description, duration_minutes, price, is_active, display_order").eq("business_id", business_id).order("display_order", { ascending: true });
    if (!include_inactive) query = query.eq("is_active", true);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, services: data ?? [] });
  }
});

// src/lib/mcp/tools/list-staff.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z7 } from "npm:zod@^3.25.76";
var list_staff_default = defineTool8({
  name: "list_staff",
  title: "List staff",
  description: "List the staff members of a business along with their working hours.",
  inputSchema: {
    business_id: z7.string().uuid().describe("Business id from list_businesses."),
    include_inactive: z7.boolean().optional().describe("Include deactivated staff members. Defaults to false.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ business_id, include_inactive }, ctx) => {
    const denied = requireAuth(ctx);
    if (denied) return denied;
    let query = supabaseForUser(ctx).from("staff").select("id, name, email, phone, is_active, working_hours").eq("business_id", business_id).order("name");
    if (!include_inactive) query = query.eq("is_active", true);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, staff: data ?? [] });
  }
});

// src/lib/mcp/index.ts
var projectRef = "oleozgrhqfxavbmsiecf";
var mcp_default = defineMcp({
  name: "lek-bookings-mcp",
  title: "LEK Bookings",
  version: "0.1.0",
  instructions: "Tools for the LEK Bookings appointment system. Start with `list_businesses` to get a business_id, then use `list_services`, `list_staff`, `list_customers` and `list_bookings` to read the diary, `create_booking` and `create_customer` to add records, and `update_booking_status` to confirm, complete or cancel an appointment. All data is scoped to the signed-in user's permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_businesses_default,
    list_bookings_default,
    create_booking_default,
    update_booking_status_default,
    list_customers_default,
    create_customer_default,
    list_services_default,
    list_staff_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
